name: RECOVERY

on:
  workflow_dispatch:
    inputs:
      RECOVERY_URL:
        description: 'RECOVERY URL'
        required: true
        default: 'https://transfer.sh/(RECOMMENDED)'

env:
  RECOVERY_URL: https://download1584.mediafire.com/ej9b3zs5wurgRy5zmfqeCw0ErW45K0Zk6dO7vuk5g-cUyEf_IG4uEUA91VrSskfF8GdrWSkYKEbhFRRTYV2GpfCSqG7dk8UTXfEimmRzPmz-s0sSgarLnh4c_pn8c0lC9w4Uf9dYZ8QJ-KLHoogPautzQm1yZqaZkRUfRxXJXtdGrw/j4sk7z8j8nv0zle/recovery.img

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out
      uses: actions/checkout@main

    - name: Prepare the environment
      run: |
        sudo apt install git wget lz4 tar openssl python3 -y

    - name: Fetch image from URL
      run: |
        ls
        pwd
        wget ${{github.event.inputs.RECOVERY_URL }}

    - name: Patch Process-1
      run: |
        chmod a+x script1.sh
        chmod a+x magiskboot
        ./script1.sh || true

    - name: Patch Process-2
      run: |
        chmod a+x script2.sh
        ./script2.sh || true
        python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
        python3 avbtool add_hash_footer --partition_name recovery --partition_size $(wc -c recovery.img |cut -f 1 -d ' ') --image recovery-patched.img --key phh.pem --algorithm SHA256_RSA4096
        mkdir output && cd output
        mv ../recovery-patched.img recovery.img
        tar cvf fastbootd-recovery.tar recovery.img
        md5sum -t fastbootd-recovery.tar >> fastbootd-recovery.tar
        mv fastbootd-recovery.tar fastbootd-recovery.tar.md5

    - name: Upload Recovery
      uses: actions/upload-artifact@v3.0.0
      with:
        path: /home/runner/work/Patch-Recovery/Patch-Recovery/output/*.md5
        name: Patched-Recovery
